### PR TITLE
Layout

### PR DESCRIPTION
**Pull request by vananhtran**

### CODE REVIEW

**Comment by vananhtran** [comment]
LGTM

**Comment by vananhtran** [comment]
ready

**Comment by huuphuc93** [comment]
Commented
191 file (luon), tách làm 10 pull cho anh

**Comment by vananhtran** [comment]
ready

**Comment by vananhtran** [comment]
ready

**Comment by vananhtran** [comment]
ready

**Comment by vananhtran** [comment]
ready

**Comment by vananhtran** [comment]
ready

**Comment by vananhtran** [comment]
ready

**Pull request merged**
